#+title: Taurus
#+subtitle: Taurus parses Call logs
#+export_file_name: index
#+setupfile: ~/.emacs.d/org-templates/projects.org
#+startup: overview

| Website         | https://andinus.nand.sh/taurus             |
| Source          | https://git.tilde.institute/andinus/taurus |
| GitHub (mirror) | https://github.com/andinus/taurus          |

* Demo

This was recorded with ~asciinema~.

[[https://asciinema.org/a/431154][https://asciinema.org/a/431154.png]]

+ Taurus v0.1.1: https://asciinema.org/a/431154
+ alt-link (download): https://andinus.nand.sh/static/taurus

* Installation

Taurus is released to ~fez~, you can get it from there or install it from
source. In any case, ~zef~ is required to install the distribution.

You can run Taurus without ~zef~. Just run ~raku -Ilib bin/taurus~ from
within the source directory.

** Release

1. Run ~zef install taurus~.

Taurus should be installed, try running ~taurus --version~ to confirm.

** From Source

You can either download the release archive generated by cgit/GitHub or
clone the project if you have ~git~ installed.

*** Without ~git~

1. Download the release:
   - https://git.tilde.institute/andinus/taurus
   - https://github.com/andinus/taurus/releases
2. Extract the file.
3. Run ~zef install .~ in source directory.

*** With ~git~

All commits will be signed by my [[https://andinus.nand.sh/static/D9AE4AEEE1F1B3598E81D9DFB67D55D482A799FD.asc][PGP Key]].

#+begin_src sh
# Clone the project.
git clone https://git.tilde.institute/andinus/taurus
cd taurus

# Install taurus.
zef install .
#+end_src

* Documentation

Taurus parses Call logs exported by [[https://f-droid.org/en/packages/opencontacts.open.com.opencontacts/][OpenContacts]]. Get the application
from F-Droid and export the call logs by selecting /More/, then /Export
call log/ from the three dot menu on top right.

** Implementation

It parses the exported log file line by line, stores them & presents an
interface.

** Options

*** log

Exported log file.

*** digits

Number of significant digits in phone numbers. Default is set to 10. If
the number of digits is less than significant digits then the number is
discarded, if it's more then the initial extra digits are discarded
(Country Code, etc.).
* News

** v0.1.1 - 2021-08-19

+ Better format for timestamps.
+ Add Yearly Records.
+ Add Monthly Records.

** v0.1.0 - 2021-08-15

Initial Implementation.

+ Present overall stats.
+ Displays contact specific stats.
  + Outgoing
  + Incoming
  + Total Call Time
  + Declined
  + They Declined
  + Missed Calls
